In [1]:
import pandas as pd

In [9]:
df_wind_trubaduren = pd.read_csv('../data/smhi_wind_data_trubaduren.csv', sep=';', usecols=[0, 1, 2, 3, 4, 5], header=7)

In [10]:
df_wind_trubaduren = df_wind_trubaduren.rename(columns=({'Tid (UTC)': 'Tid_UTC', 'Kvalitet.1': 'Kvalitet_1'}))

In [11]:
df_wind_trubaduren

             Datum   Tid_UTC  Vindriktning Kvalitet  Vindhastighet Kvalitet_1
0       1978-12-12  15:00:00         110.0        Y            6.0          Y
1       1978-12-12  21:00:00         110.0        Y            7.0          Y
2       1978-12-13  03:00:00          80.0        Y            6.0          Y
3       1978-12-13  09:00:00          90.0        Y            6.0          Y
4       1978-12-13  15:00:00         100.0        Y            8.0          Y
...            ...       ...           ...      ...            ...        ...
150492  2007-06-11  07:00:00         282.0        Y            3.5          Y
150493  2007-06-11  08:00:00         265.0        Y            2.4          Y
150494  2007-06-11  09:00:00         247.0        G            3.5          G
150495  2007-06-11  10:00:00         253.0        Y            2.2          Y
150496  2007-06-11  11:00:00         265.0        Y            2.9          Y

[150497 rows x 6 columns]

In [12]:
df_wind_trubaduren['Datum'] = pd.to_datetime(df_wind_trubaduren['Datum'])

In [13]:
df_wind_trubaduren['Vindhastighet_snitt'] = df_wind_trubaduren.groupby('Datum')['Vindhastighet'].transform('mean').round(2)
df_wind_trubaduren['Högsta_vindhastighet'] = df_wind_trubaduren.groupby('Datum')['Vindhastighet'].transform('max').round(2)
df_wind_trubaduren['Year'] = df_wind_trubaduren['Datum'].dt.year
df_wind_trubaduren['Month'] = df_wind_trubaduren['Datum'].dt.month

In [14]:
df_wind_trubaduren

,Datum,Tid_UTC,Vindriktning,Kvalitet,Vindhastighet,Kvalitet_1,Vindhastighet_snitt,Högsta_vindhastighet,Year,Month
0,1978-12-12,15:00:00,110.0,Y,6.0,Y,6.50,7.0,1978,12
1,1978-12-12,21:00:00,110.0,Y,7.0,Y,6.50,7.0,1978,12
2,1978-12-13,03:00:00,80.0,Y,6.0,Y,7.25,9.0,1978,12
3,1978-12-13,09:00:00,90.0,Y,6.0,Y,7.25,9.0,1978,12
4,1978-12-13,15:00:00,100.0,Y,8.0,Y,7.25,9.0,1978,12
...,...,...,...,...,...,...,...,...,...,...
150492,2007-06-11,07:00:00,282.0,Y,3.5,Y,2.27,3.5,2007,6
150493,2007-06-11,08:00:00,265.0,Y,2.4,Y,2.27,3.5,2007,6
150494,2007-06-11,09:00:00,247.0,G,3.5,G,2.27,3.5,2007,6
150495,2007-06-11,10:00:00,253.0,Y,2.2,Y,2.27,3.5,2007,6
150496,2007-06-11,11:00:00,265.0,Y,2.9,Y,2.27,3.5,2007,6

In [15]:
df_wind_trubaduren['Year'].nunique()

30

In [16]:
2007-1978

29

In [20]:
years_present = []
for ind, val in enumerate(df_wind_trubaduren['Year'].groupby(df_wind_trubaduren['Year'])):
    years_present.append(val[0])

In [21]:
for i in range(1978, 2007):
    if i in years_present:
        pass
    else:
        print(i)

In [22]:
df_wind_trubaduren.to_pickle('../Dataframes/df_wind_trubaduren.pkl')